export { default as OverviewTab } from "./OverviewTab";
export { default as ScheduleTab } from "./ScheduleTab";
export { default as StandingsTab } from "./StandingsTab";
export { default as LiveScoreControllerTab } from "./LiveScoreControllerTab";
export { default as ResultsSubmissionTab } from "./ResultsSubmissionTab";
export { default as MatchControlCenterTab } from "./MatchControlCenterTab";
export { default as MatchResultsReviewTab } from "./MatchResultsReviewTab";
export { default as PlayersTab } from "./PlayersTab";
export { default as RefereesTab } from "./RefereesTab";
